### ISSUE TITLE
Task: Create a database API

### ISSUE THREAD

**Issue by schan219** [CodeTheChangeUBC/sasc#16]
Deadline: Please complete before Friday July 7th, 2017.

We need the following functions in our db API:

User-related functions:
1. adding a user
2. updating a user's fields**
3. deleting a user*
4. get user information from db

Counselor-related functions:
1. adding a counselor
2. updating a counselor's fields**
3. deleting a counselor
4. get user information from db

Session-related functions:
1. adding a session
2. deleting a session*
3. get session info from db
4. updating a session's end time
5. updating a session's begin time*

*These functions are for development purposes. In the actual application we will not be using these.

**The update function for users and counselors will require dynamic SQL generation (assuming we are using raw SQL queries). For example, users can choose to update the first name field, but not last name or anything else. The corresponding SQL query generated at run time must only update the first name field, in that case.

***Primary keys should not be alterable by update.

**Comment by bchugg** [comment]
@schan219 Can this be closed?
