### ISSUE TITLE
Change user number field to char

### ISSUE THREAD

**Issue by bchugg** [CodeTheChangeUBC/sasc#26]
Integer is too short and doesn't allow formatting.

**Comment by schan219** [comment]
How about using an unsigned BIGINT? The range would be from 0 to 18446744073709551615. That way we can keep AUTO_INCREMENT. What kind of formatting do you need for user ID?

**Comment by bchugg** [comment]
@schan219 Sorry, by the user number field I meant phone number (maybe I should change the name too?).

**Comment by schan219** [comment]
Oh, my bad. Yeah, let's call it phoneNumber to avoid confusion. And I also agree that phoneNumber should be string instead of int. Maybe we could use VARCHAR(15).

**Comment by bchugg** [comment]
Sounds good - I'll make the change.
