### ISSUE TITLE
Which spelling of the word "counselor" are we using?

### ISSUE THREAD

**Issue by joe-tom** [CodeTheChangeUBC/sasc#35]
Only making this an issue because I've seen different spellings, mainly **Counselor** and **Counsellor**.
It's better if we decide on one spelling for consistency's sake.

**Comment by bchugg** [comment]
The model that @schan219 wrote is spelled counsellor.

**Comment by joe-tom** [comment]
@schan219 What say ye?

**Comment by schan219** [comment]
Let's go with the Canadian spelling "counsellor".
